# -*- coding: utf-8 -*-
"""First-publication (or composition) year per CLT addition.

Same posture as first_pub.py: a curated table somebody can read and correct,
not a lookup that changes silently between builds. Negative years are BC.
`circa` marks a date the scholarship gives as approximate. None means the date
was not settled here and the card shows no year rather than a guess.
"""
# bank entry -> (year, circa)
YEARS = {
    "Hesiod": (-700, True), "Aeschylus": (-430, True),
    "Herodotus": (-430, True), "Euripides": (-431, False),
    "Thucydides": (-400, True), "Hippocrates": (-400, True),
    "Euclid": (-300, True), "Archimedes": (-250, True),
    "Terence": (-165, True), "Cicero": (-44, False),
    "Julius Caesar": (-51, False), "Lucretius": (-55, True),
    "Livy": (-27, True), "Ovid": (8, False),
    "Seneca the Younger": (65, True), "Josephus": (93, False),
    "Plutarch": (100, True), "Epictetus": (125, True),
    "Tacitus": (117, True), "Tertullian": (197, False),
    "Origen": (230, True), "Athanasius": (318, True),
    "Gregory of Nyssa": (392, True), "Jerome": (400, True),
    "Augustine of Hippo": (400, False), "Boethius": (524, True),
    "Benedict": (540, True), "Procopius": (550, True),
    "Gregory the Great": (591, False), "Bede the Venerable": (731, False),
    "Avicenna": (1027, True), "Anselm of Canterbury": (1078, False),
    "Peter Abelard": (1132, True), "Bernard of Clairvaux": (1126, True),
    "Hugh of St. Victor": (1127, True), "Hildegard of Bingen": (1151, False),
    "Heloise d'Argenteuil": (1135, True), "Averroes": (1180, True),
    "Moses Maimonides": (1190, False), "Marie de France": (1170, True),
    "Thomas Aquinas": (1274, False), "Giovanni Boccaccio": (1353, False),
    "John Wycliffe": (1380, True), "Julian of Norwich": (1395, True),
    "Catherine of Siena": (1378, False), "Christine de Pizan": (1405, False),
    "Thomas a Kempis": (1427, True), "Thomas Malory": (1485, False),
    "Pearl": (1380, True),
    "Desiderius Erasmus": (1511, False), "Niccolo Machiavelli": (1532, False),
    "Nicolaus Copernicus": (1543, False), "Thomas More": (1516, False),
    "Martin Luther": (1517, False), "Bartolome de Las Casas": (1552, False),
    "John Calvin": (1536, False), "Teresa of Avila": (1588, False),
    "Michel de Montaigne": (1580, False), "Francis Bacon": (1597, False),
    "Galileo Galilei": (1610, False), "John Donne": (1624, False),
    "Thomas Hobbes": (1651, False), "Rene Descartes": (1637, False),
    "John Milton": (1667, False), "Blaise Pascal": (1670, False),
    "Margaret Cavendish": (1666, False), "Robert Boyle": (1661, False),
    "John Bunyan": (1678, False), "John Locke": (1689, False),
    "Isaac Newton": (1704, False), "Gottfried Leibniz": (1710, False),
    "Charles Montesquieu": (1748, False), "Voltaire": (1759, False),
    "Jonathan Edwards": (1741, False), "Benjamin Franklin": (1791, False),
    "David Hume": (1748, False), "Jean-Jacques Rousseau": (1762, False),
    "Adam Smith": (1776, False), "Immanuel Kant": (1785, False),
    "Edward Gibbon": (1776, False), "Antoine Lavoisier": (1789, False),
    "Thomas Jefferson": (1776, False), "Olaudah Equiano": (1789, False),
    "Johann Wolfgang von Goethe": (1808, False),
    "Mary Wollstonecraft": (1792, False), "Georg W. F. Hegel": (1837, False),
    "Jakob & Wilhelm Grimm": (1812, False), "Sojourner Truth": (1850, False),
    "John Henry Newman": (1864, False), "Alexis de Tocqueville": (1835, False),
    "John Stuart Mill": (1859, False), "Edgar Allan Poe": (1845, False),
    "Charles Darwin": (1859, False), "Soren Kierkegaard": (1843, False),
    "Henry David Thoreau": (1854, False), "Karl Marx": (1848, False),
    "George Eliot": (1872, False), "Herman Melville": (1851, False),
    "Susan B. Anthony": (1881, False), "Gregor Mendel": (1866, False),
    "Louis Pasteur": (1876, False), "Leo Tolstoy": (1869, False),
    "Oscar Wilde": (1895, False), "Sigmund Freud": (1920, False),
    "Anna Julia Cooper": (1892, False), "Anton Chekhov": (1898, False),
    "Alfred North Whitehead": (1911, False), "Ida B. Wells": (1892, False),
    "W. E. B. Du Bois": (1903, False), "Mahatma Gandhi": (1922, False),
    "Willa Cather": (1918, False), "G. K. Chesterton": (1908, False),
    "Albert Einstein": (1916, False), "John Maynard Keynes": (1919, False),
    "Ludwig Wittgenstein": (1921, False), "Dorothy Sayers": (1923, False),
    "Ernest Hemingway": (1952, False), "Jorge Luis Borges": (1944, False),
    "Friedrich Hayek": (1944, False), "Hannah Arendt": (1958, False),
    "Albert Camus": (1942, False), "Aleksandr Solzhenitsyn": (1962, False),
    "James Baldwin": (1963, False), "Martin Luther King Jr.": (1963, False),
    "Toni Morrison": (1987, False),
    "The Epic of Gilgamesh": (-1800, True),
    "The Nibelungenlied": (1200, True),
    "Magna Carta": (1215, False),
    "The Saga of Erik the Red": (1265, True),
}

# Works composed in English. Everything else reaches a student in translation,
# which is what the free-vs-buy signposting turns on.
ENGLISH_ORIGINAL = {
    "Julian of Norwich", "Thomas Malory", "Francis Bacon", "John Donne",
    "Thomas Hobbes", "John Milton", "Margaret Cavendish", "Robert Boyle",
    "John Bunyan", "John Locke", "Isaac Newton", "Jonathan Edwards",
    "Benjamin Franklin", "David Hume", "Adam Smith", "Edward Gibbon",
    "Thomas Jefferson", "Olaudah Equiano", "Mary Wollstonecraft",
    "Sojourner Truth", "John Henry Newman", "John Stuart Mill",
    "Edgar Allan Poe", "Charles Darwin", "Henry David Thoreau",
    "George Eliot", "Herman Melville", "Susan B. Anthony", "Oscar Wilde",
    "Anna Julia Cooper", "Alfred North Whitehead", "Ida B. Wells",
    "W. E. B. Du Bois", "Willa Cather", "G. K. Chesterton",
    "John Maynard Keynes", "Dorothy Sayers", "Ernest Hemingway",
    "Friedrich Hayek", "Hannah Arendt", "James Baldwin",
    "Martin Luther King Jr.", "Toni Morrison",
    "Pearl", "John Wycliffe",
}
# Deliberately NOT here: More's Utopia and Bede's Ecclesiastical History were
# both written in Latin, however English their authors were.
