# -*- coding: utf-8 -*-
"""Editorial selection: one representative work per unrepresented CLT bank entry.

(bank_entry, work_title, display_author, pg_author_token)

pg_author_token is the surname/keyword used to locate the author in the
Gutenberg catalogue; None means the entry is an anonymous work and must be
matched on title instead.
"""
SEL = [
 ("Hesiod", "Works and Days", "Hesiod", "hesiod"),
 ("Confucius", "The Analects", "Confucius", "confucius"),
 ("Aeschylus", "Prometheus Bound", "Aeschylus", "aeschylus"),
 ("Herodotus", "The Histories", "Herodotus", "herodotus"),
 ("Euripides", "Medea", "Euripides", "euripides"),
 ("Thucydides", "History of the Peloponnesian War", "Thucydides", "thucydides"),
 ("Hippocrates", "On Airs, Waters, and Places", "Hippocrates", "hippocrates"),
 ("Euclid", "The Elements", "Euclid", "euclid"),
 ("Archimedes", "Geometrical Solutions Derived from Mechanics", "Archimedes", "archimedes"),
 ("Terence", "The Comedies of Terence", "Terence", "terence"),
 ("Cicero", "On Duties (De Officiis)", "Marcus Tullius Cicero", "cicero"),
 ("Julius Caesar", "Commentaries on the Gallic War", "Julius Caesar", "caesar"),
 ("Lucretius", "On the Nature of Things", "Lucretius", "lucretius"),
 ("Livy", "The History of Rome", "Livy", "livy"),
 ("Ovid", "Metamorphoses", "Ovid", "ovid"),
 ("Seneca the Younger", "Letters from a Stoic", "Seneca the Younger", "seneca"),
 ("Josephus", "The Antiquities of the Jews", "Flavius Josephus", "josephus"),
 ("Plutarch", "Plutarch's Lives", "Plutarch", "plutarch"),
 ("Epictetus", "The Enchiridion", "Epictetus", "epictetus"),
 ("Tacitus", "The Annals", "Tacitus", "tacitus"),
 ("Tertullian", "Apology", "Tertullian", "tertullian"),
 ("Origen", "On First Principles (De Principiis)", "Origen", "origen"),
 ("Athanasius", "On the Incarnation", "Athanasius", "athanasius"),
 ("Gregory of Nyssa", "The Life of Moses", "Gregory of Nyssa", "gregory"),
 ("Jerome", "The Letters of St. Jerome", "Jerome", "jerome"),
 ("Augustine of Hippo", "Confessions", "Augustine of Hippo", "augustine"),
 ("Boethius", "The Consolation of Philosophy", "Boethius", "boethius"),
 ("Benedict", "The Rule of St. Benedict", "Benedict of Nursia", "benedict"),
 ("Procopius", "The Secret History", "Procopius", "procopius"),
 ("Gregory the Great", "The Book of Pastoral Rule", "Gregory the Great", "gregory"),
 ("Bede the Venerable", "Ecclesiastical History of the English People", "Bede", "bede"),
 ("Avicenna", "The Canon of Medicine", "Avicenna", "avicenna"),
 ("Anselm of Canterbury", "Proslogium and Cur Deus Homo", "Anselm of Canterbury", "anselm"),
 ("Peter Abelard", "The Story of My Misfortunes", "Peter Abelard", "abelard"),
 ("Bernard of Clairvaux", "On Loving God", "Bernard of Clairvaux", "bernard"),
 ("Hugh of St. Victor", "The Didascalicon", "Hugh of St. Victor", "hugh"),
 ("Hildegard of Bingen", "Scivias", "Hildegard of Bingen", "hildegard"),
 ("Heloise d'Argenteuil", "The Letters of Abelard and Heloise", "Heloise d'Argenteuil", "heloise"),
 ("Averroes", "The Decisive Treatise", "Averroes", "averroes"),
 ("Moses Maimonides", "The Guide for the Perplexed", "Moses Maimonides", "maimonides"),
 ("Marie de France", "The Lays of Marie de France", "Marie de France", "marie"),
 ("Thomas Aquinas", "Summa Theologica", "Thomas Aquinas", "aquinas"),
 ("Giovanni Boccaccio", "The Decameron", "Giovanni Boccaccio", "boccaccio"),
 ("John Wycliffe", "Select English Works", "John Wycliffe", "wycliffe"),
 ("Julian of Norwich", "Revelations of Divine Love", "Julian of Norwich", "julian"),
 ("Catherine of Siena", "The Dialogue of St. Catherine of Siena", "Catherine of Siena", "catherine"),
 ("Christine de Pizan", "The Book of the City of Ladies", "Christine de Pizan", "christine"),
 ("Thomas a Kempis", "The Imitation of Christ", "Thomas a Kempis", "kempis"),
 ("Thomas Malory", "Le Morte d'Arthur", "Thomas Malory", "malory"),
 ("Desiderius Erasmus", "The Praise of Folly", "Desiderius Erasmus", "erasmus"),
 ("Niccolo Machiavelli", "The Prince", "Niccolo Machiavelli", "machiavelli"),
 ("Nicolaus Copernicus", "On the Revolutions of the Heavenly Spheres", "Nicolaus Copernicus", "copernicus"),
 ("Thomas More", "Utopia", "Thomas More", "more"),
 ("Martin Luther", "The Ninety-Five Theses", "Martin Luther", "luther"),
 ("Bartolome de Las Casas", "A Brief Account of the Destruction of the Indies", "Bartolome de Las Casas", "casas"),
 ("John Calvin", "Institutes of the Christian Religion", "John Calvin", "calvin"),
 ("Teresa of Avila", "The Interior Castle", "Teresa of Avila", "teresa"),
 ("Michel de Montaigne", "Essays", "Michel de Montaigne", "montaigne"),
 ("Francis Bacon", "Essays", "Francis Bacon", "bacon"),
 ("Galileo Galilei", "Dialogues Concerning Two New Sciences", "Galileo Galilei", "galilei"),
 ("John Donne", "Devotions upon Emergent Occasions", "John Donne", "donne"),
 ("Thomas Hobbes", "Leviathan", "Thomas Hobbes", "hobbes"),
 ("Rene Descartes", "Discourse on Method", "Rene Descartes", "descartes"),
 ("John Milton", "Paradise Lost", "John Milton", "milton"),
 ("Blaise Pascal", "Pensees", "Blaise Pascal", "pascal"),
 ("Margaret Cavendish", "The Blazing World", "Margaret Cavendish", "cavendish"),
 ("Robert Boyle", "The Sceptical Chymist", "Robert Boyle", "boyle"),
 ("John Bunyan", "The Pilgrim's Progress", "John Bunyan", "bunyan"),
 ("John Locke", "Second Treatise of Government", "John Locke", "locke"),
 ("Isaac Newton", "Opticks", "Isaac Newton", "newton"),
 ("Gottfried Leibniz", "The Monadology", "Gottfried Leibniz", "leibniz"),
 ("Charles Montesquieu", "The Spirit of Laws", "Charles de Montesquieu", "montesquieu"),
 ("Voltaire", "Candide", "Voltaire", "voltaire"),
 ("Jonathan Edwards", "Sinners in the Hands of an Angry God", "Jonathan Edwards", "edwards"),
 ("Benjamin Franklin", "The Autobiography of Benjamin Franklin", "Benjamin Franklin", "franklin"),
 ("David Hume", "An Enquiry Concerning Human Understanding", "David Hume", "hume"),
 ("Jean-Jacques Rousseau", "The Social Contract", "Jean-Jacques Rousseau", "rousseau"),
 ("Adam Smith", "The Wealth of Nations", "Adam Smith", "smith"),
 ("Immanuel Kant", "Fundamental Principles of the Metaphysic of Morals", "Immanuel Kant", "kant"),
 ("Edward Gibbon", "The History of the Decline and Fall of the Roman Empire", "Edward Gibbon", "gibbon"),
 ("Antoine Lavoisier", "Elements of Chemistry", "Antoine Lavoisier", "lavoisier"),
 ("Thomas Jefferson", "The Declaration of Independence", "Thomas Jefferson", "jefferson"),
 ("Olaudah Equiano", "The Interesting Narrative of the Life of Olaudah Equiano", "Olaudah Equiano", "equiano"),
 ("Johann Wolfgang von Goethe", "Faust", "Johann Wolfgang von Goethe", "goethe"),
 ("James Madison", "Notes of the Secret Debates of the Federal Convention", "James Madison", "madison"),
 ("Mary Wollstonecraft", "A Vindication of the Rights of Woman", "Mary Wollstonecraft", "wollstonecraft"),
 ("Georg W. F. Hegel", "The Philosophy of History", "Georg W. F. Hegel", "hegel"),
 ("Jakob & Wilhelm Grimm", "Grimms' Fairy Tales", "Jakob and Wilhelm Grimm", "grimm"),
 ("Sojourner Truth", "The Narrative of Sojourner Truth", "Sojourner Truth", "truth"),
 ("John Henry Newman", "Apologia Pro Vita Sua", "John Henry Newman", "newman"),
 ("Alexis de Tocqueville", "Democracy in America", "Alexis de Tocqueville", "tocqueville"),
 ("John Stuart Mill", "On Liberty", "John Stuart Mill", "mill"),
 ("Edgar Allan Poe", "The Raven", "Edgar Allan Poe", "poe"),
 ("Charles Darwin", "On the Origin of Species", "Charles Darwin", "darwin"),
 ("Soren Kierkegaard", "Fear and Trembling", "Soren Kierkegaard", "kierkegaard"),
 ("Henry David Thoreau", "Walden", "Henry David Thoreau", "thoreau"),
 ("Karl Marx", "The Communist Manifesto", "Karl Marx", "marx"),
 ("George Eliot", "Middlemarch", "George Eliot", "eliot"),
 ("Herman Melville", "Moby-Dick", "Herman Melville", "melville"),
 ("Susan B. Anthony", "The Trial of Susan B. Anthony", "Susan B. Anthony", "anthony"),
 ("Gregor Mendel", "Experiments in Plant Hybridisation", "Gregor Mendel", "mendel"),
 ("Louis Pasteur", "The Germ Theory and Its Applications to Medicine", "Louis Pasteur", "pasteur"),
 ("Leo Tolstoy", "War and Peace", "Leo Tolstoy", "tolstoy"),
 ("Friedrich Nietzsche", "Thus Spake Zarathustra", "Friedrich Nietzsche", "nietzsche"),
 ("Oscar Wilde", "The Importance of Being Earnest", "Oscar Wilde", "wilde"),
 ("Sigmund Freud", "Dream Psychology", "Sigmund Freud", "freud"),
 ("Anna Julia Cooper", "A Voice from the South", "Anna Julia Cooper", "cooper"),
 ("Anton Chekhov", "The Cherry Orchard", "Anton Chekhov", "chekhov"),
 ("Alfred North Whitehead", "An Introduction to Mathematics", "Alfred North Whitehead", "whitehead"),
 ("Ida B. Wells", "Southern Horrors: Lynch Law in All Its Phases", "Ida B. Wells", "wells"),
 ("W. E. B. Du Bois", "The Souls of Black Folk", "W. E. B. Du Bois", "bois"),
 ("Mahatma Gandhi", "An Autobiography: The Story of My Experiments with Truth", "Mahatma Gandhi", "gandhi"),
 ("Willa Cather", "My Antonia", "Willa Cather", "cather"),
 ("G. K. Chesterton", "Orthodoxy", "G. K. Chesterton", "chesterton"),
 ("Albert Einstein", "Relativity: The Special and General Theory", "Albert Einstein", "einstein"),
 ("John Maynard Keynes", "The Economic Consequences of the Peace", "John Maynard Keynes", "keynes"),
 ("Ludwig Wittgenstein", "Tractatus Logico-Philosophicus", "Ludwig Wittgenstein", "wittgenstein"),
 ("Dorothy Sayers", "Whose Body?", "Dorothy L. Sayers", "sayers"),
 ("Ernest Hemingway", "The Old Man and the Sea", "Ernest Hemingway", "hemingway"),
 ("Jorge Luis Borges", "Ficciones", "Jorge Luis Borges", "borges"),
 ("Friedrich Hayek", "The Road to Serfdom", "Friedrich Hayek", "hayek"),
 ("Hannah Arendt", "The Human Condition", "Hannah Arendt", "arendt"),
 ("Albert Camus", "The Stranger", "Albert Camus", "camus"),
 ("Aleksandr Solzhenitsyn", "One Day in the Life of Ivan Denisovich", "Aleksandr Solzhenitsyn", "solzhenitsyn"),
 ("James Baldwin", "The Fire Next Time", "James Baldwin", "baldwin"),
 ("Martin Luther King Jr.", "Letter from Birmingham Jail", "Martin Luther King Jr.", "king"),
 ("Toni Morrison", "Beloved", "Toni Morrison", "morrison"),
 ("The Epic of Gilgamesh", "The Epic of Gilgamesh", "Anonymous", None),
 ("The Nibelungenlied", "The Nibelungenlied", "Anonymous", None),
 ("Magna Carta", "Magna Carta", "Anonymous", None),
 ("The Saga of Erik the Red", "The Saga of Erik the Red", "Anonymous", None),
 ("Pearl", "Pearl", "Anonymous", None),
]
